//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knockout_JS_CRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat
    {
        public int id { get; set; }
        public string name { get; set; }
        public string breed { get; set; }
        public string sex { get; set; }
        public string age { get; set; }
    }
}
